/*
 * Copyright (C) 2016 LINUXTEK, Inc.  All Rights Reserved.
 */
package com.linuxtek.kona.data.mybatis;

import java.util.List;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.JavaVisibility;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.api.dom.java.PrimitiveTypeWrapper;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.mybatis.generator.api.dom.xml.Attribute;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;

/**
 * Plugin Lifecycle
 * <ol>
 * <li>default constructor
 * <li>{@link #setContext(org.mybatis.generator.config.Context)}
 * <li>{@link #setProperties(java.util.Properties)}
 * <li>{@link #validate(List)}
 *      <br>If this method returns false, then no further methods in the plugin will be called
 * <li>For each table<ol>
 *      <li>{@link #initialized(IntrospectedTable)}
 *      <li>Java Client Methods
 *          <ol>
 *              <li>client___MethodGenerated(Method, TopLevelClass, IntrospectedTable)
 *                  <br>- each method of a Java client implementation
 *              <li>client___MethodGenerated(Method, Interface, IntrospectedTable)
 *                  <br>- each method of a Java client interface
 *              <li>{@link #clientGenerated(org.mybatis.generator.api.dom.java.Interface, TopLevelClass, IntrospectedTable)}
 *          </ol>
 *      <li>Model Methods
 *          <ol>
 *              <li>for each field
 *                  <br>{@link #modelFieldGenerated(Field, TopLevelClass, org.mybatis.generator.api.IntrospectedColumn, IntrospectedTable, org.mybatis.generator.api.Plugin.ModelClassType)}
 *                  <br>{@link #modelGetterMethodGenerated(Method, TopLevelClass, org.mybatis.generator.api.IntrospectedColumn, IntrospectedTable, org.mybatis.generator.api.Plugin.ModelClassType)}
 *                  <br>{@link #modelSetterMethodGenerated(Method, TopLevelClass, org.mybatis.generator.api.IntrospectedColumn, IntrospectedTable, org.mybatis.generator.api.Plugin.ModelClassType)}
 *              <li>{@link #modelExampleClassGenerated(TopLevelClass, IntrospectedTable)}
 *              <li>{@link #modelPrimaryKeyClassGenerated(TopLevelClass, IntrospectedTable)}
 *              <li>{@link #modelBaseRecordClassGenerated(TopLevelClass, IntrospectedTable)}
 *              <li>{@link #modelRecordWithBLOBsClassGenerated(TopLevelClass, IntrospectedTable)}
 *          </ol>
 *      <li>SQL Map Methods
 *          <ol>
 *              <li>sqlMap___ElementGenerated(XmlElement, IntrospectedTable)
 *                  <br>- each element of the SQL map
 *              <li>{@link #sqlMapDocumentGenerated(org.mybatis.generator.api.dom.xml.Document, IntrospectedTable)}
 *              <li>sqlMapDocument(GeneratedXmlFile, IntrospectedTable)
 *          </ol>
 *      <li>{@link #contextGenerateAdditionalJavaFiles(IntrospectedTable)}
 *      <li>{@link #contextGenerateAdditionalXmlFiles(IntrospectedTable)}
 * </ol>
 * <li>{@link #contextGenerateAdditionalJavaFiles()}
 * <li>{@link #contextGenerateAdditionalXmlFiles()}
 * </ol>
 *
 * @author challengek
 *
 */
public class KLimitPlugin extends PluginAdapter {
    
    private final String javadocField = "/**\r\n" + 
            "     * This field was generated by MyBatis Generator.\r\n" + 
            "     * This field corresponds to the database table users\r\n" + 
            "     *\r\n" + 
            "     * @mbggenerated\r\n" + 
            "     */";
    
    private final String javadocMethod = "/**\r\n" + 
            "     * This method was generated by MyBatis Generator.\r\n" + 
            "     * This method corresponds to the database table users\r\n" + 
            "     *\r\n" + 
            "     * @mbggenerated\r\n" + 
            "     */";
    
    
    public boolean validate(List<String> arg0) {
        return true;
    }
    
    
    /* (non-Javadoc)
     * @see org.mybatis.generator.api.PluginAdapter#sqlMapSelectByExampleWithBLOBsElementGenerated(org.mybatis.generator.api.dom.xml.XmlElement, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public boolean sqlMapSelectByExampleWithBLOBsElementGenerated(XmlElement element,
            IntrospectedTable introspectedTable) {
        //FullyQualifiedTable table = introspectedTable.getFullyQualifiedTable();
    
        //XmlElement lastElement = (XmlElement)element.getElements().get(element.getElements().size());
    
        XmlElement isNotNullElement = new XmlElement("if");
        isNotNullElement.addAttribute(new Attribute("test", "limit != null"));
        isNotNullElement.addElement(new TextElement("limit ${limit}"));
        element.getElements().add(isNotNullElement);
    
    
        isNotNullElement = new XmlElement("if");
        isNotNullElement.addAttribute(new Attribute("test", "offset != null"));
        isNotNullElement.addElement(new TextElement("offset ${offset}"));
        element.getElements().add(isNotNullElement);
        
        return super.sqlMapSelectByExampleWithBLOBsElementGenerated(element, introspectedTable);
    }
    
    /* (non-Javadoc)
     * @see org.mybatis.generator.api.PluginAdapter#sqlMapSelectByExampleWithoutBLOBsElementGenerated(org.mybatis.generator.api.dom.xml.XmlElement, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public boolean sqlMapSelectByExampleWithoutBLOBsElementGenerated(XmlElement element,
            IntrospectedTable introspectedTable) {
        
        XmlElement isNotNullElement = new XmlElement("if");
        isNotNullElement.addAttribute(new Attribute("test", "limit != null"));
        isNotNullElement.addElement(new TextElement("limit ${limit}"));
        element.getElements().add(isNotNullElement);
        
        isNotNullElement = new XmlElement("if");
        isNotNullElement.addAttribute(new Attribute("test", "offset != null"));
        isNotNullElement.addElement(new TextElement("offset ${offset}"));
        element.getElements().add(isNotNullElement);
        
        return super.sqlMapSelectByExampleWithoutBLOBsElementGenerated(element, introspectedTable);
    }



    /* (non-Javadoc)
     * @see org.mybatis.generator.api.PluginAdapter#modelExampleClassGenerated(org.mybatis.generator.api.dom.java.TopLevelClass, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public boolean modelExampleClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        
        PrimitiveTypeWrapper integerWrapper = FullyQualifiedJavaType.getIntInstance().getPrimitiveTypeWrapper();
        
        Field limit = new Field();
        limit.setName("limit");
        limit.setVisibility(JavaVisibility.PRIVATE);
        limit.setType(integerWrapper);
        limit.addJavaDocLine(javadocField);
        topLevelClass.addField(limit);
        

        Method limitSet = new Method();
        limitSet.setVisibility(JavaVisibility.PUBLIC);
        limitSet.setName("setLimit");
        limitSet.addParameter(new Parameter(integerWrapper, "limit"));
        limitSet.addBodyLine("this.limit = limit;");
        limitSet.addJavaDocLine(javadocMethod);
        topLevelClass.addMethod(limitSet);

        Method limitGet = new Method();
        limitGet.setVisibility(JavaVisibility.PUBLIC);
        limitGet.setReturnType(integerWrapper);
        limitGet.setName("getLimit");
        limitGet.addBodyLine("return limit;");
        limitGet.addJavaDocLine(javadocMethod);
        topLevelClass.addMethod(limitGet);

        Field offset = new Field();
        offset.setName("offset");
        offset.setVisibility(JavaVisibility.PRIVATE);
        offset.setType(integerWrapper);
        offset.addJavaDocLine(javadocField);
        topLevelClass.addField(offset);
        
        Method offsetSet = new Method();
        offsetSet.setVisibility(JavaVisibility.PUBLIC);
        offsetSet.setName("setOffset");
        offsetSet.addParameter(new Parameter(integerWrapper, "offset"));
        offsetSet.addBodyLine("this.offset = offset;");
        offsetSet.addJavaDocLine(javadocMethod);
        topLevelClass.addMethod(offsetSet);

        Method offsetGet = new Method();
        offsetGet.setVisibility(JavaVisibility.PUBLIC);
        offsetGet.setReturnType(integerWrapper);
        offsetGet.setName("getOffset");
        offsetGet.addBodyLine("return offset;");
        offsetGet.addJavaDocLine(javadocMethod);
        topLevelClass.addMethod(offsetGet);
        
        return super.modelExampleClassGenerated(topLevelClass, introspectedTable);
    }
}
